# .github/workflows/vertex-ai-trigger.yml
name: Trigger Vertex AI Pipeline

on:
  push:
    branches:
      - master

jobs:
  publish-message:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: timestack-casestudy-bhathiya
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Publish message to Pub/Sub
      run: |
        gcloud pubsub topics publish vertex-pipeline-trigger \
          --message '{
            "project_id": "timestack-casestudy-bhathiya"
          }'
